In [ ]:
#using functions to generate data


In [7]:
import numpy as np
a33=np.ones((3,4))

In [9]:
type(a33)

numpy.ndarray

In [11]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
a44=np.zeros((2,4))

In [28]:
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [32]:
import numpy as np

In [7]:
zeros_array=np.zeros((3,3))
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [11]:
ones_array=np.ones((2,4))

In [13]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
import numpy as np

In [5]:
identity_matrix=np.eye(3)
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
l=[1,2,3,4]
np.array(l,dtype=np.int32)

array([1, 2, 3, 4])

In [19]:
import numpy as np
int_array=np.array([1,2,3,4],dtype=np.int32)
float_array=np.array([0.1,0.2,0.3],dtype=np.float64)


In [29]:
a44=np.arange(0,12)            #last ele will be excluded

In [31]:
a44

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [33]:
num=np.arange(10,20)

In [35]:
num

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [37]:
linspace_array_2=np.linspace(0,10,6)

In [39]:
linspace_array_2

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [45]:
linspace=np.linspace(0,15,3)

In [47]:
linspace

array([ 0. ,  7.5, 15. ])

In [49]:
zeros_array=np.zeros((3,3))

In [51]:
ones_array=np.ones((2,4))

In [53]:
identity_matrix=np.eye(3)

In [55]:
random_array=np.random.rand(4,4)

In [57]:
random_array

array([[0.4551673 , 0.16441146, 0.49978075, 0.74007707],
       [0.96926663, 0.80172225, 0.95088347, 0.58889308],
       [0.53395494, 0.50865042, 0.51596116, 0.64419847],
       [0.9027914 , 0.64390399, 0.25830882, 0.81016198]])

In [59]:
zeros_array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
ones_array

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [63]:
identity_matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [65]:
#indexing

In [67]:
import numpy as np

In [69]:
arr=np.array([10,20,30,40])
print(arr[0])                     #basic

10


In [71]:
print(arr[-2])

30


In [73]:
print(arr[3])

40


In [75]:
matrix=np.array([[1,2,3],
                [4,5,6]])
print(matrix[0,1])                       #first row,second column
print(matrix[1,2])

2
6


In [79]:
print(matrix[0,2])

3


In [81]:
#numpy array slicing              arr[start,stop,step]

In [83]:
arr=np.array([10,20,30,40,50])

In [85]:
print(arr[1:4])

[20 30 40]


In [87]:
print(arr[:3])

[10 20 30]


In [89]:
print(arr[::-1])

[50 40 30 20 10]


In [91]:
print(arr[::2])

[10 30 50]


In [95]:
print(arr[::3])

[10 40]


In [97]:
print(arr[4:])

[50]


In [99]:
print(arr[1:])

[20 30 40 50]


In [101]:
#2d array slicing

In [103]:
matrix=np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(matrix[0:2,1:3])

[[2 3]
 [5 6]]


In [131]:
print(matrix[2:3,1:2])

[[8]]


In [133]:
print(matrix[1:3,1:2])

[[5]
 [8]]


In [135]:
#numpy array copy vs view

In [159]:
#view
a=np.array([1,2,3,4])
b=a[1:3].view()
b[0]=99
print(a)

[ 1 99  3  4]


In [153]:
#copy
a=np.array([1,2,3,4])
b=a[1:3].copy()
b[0]=99
print(a)

[1 2 3 4]


In [155]:
print(b)

[99  3]


In [161]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [173]:

a=np.arange(12)
a



array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [175]:
b=a.reshape(3,4)

In [177]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [187]:
b=a.reshape(12,1)

In [189]:
b

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [183]:
b=a.reshape(6,2)

In [185]:
b

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [191]:
b=a.reshape(1,12)

In [193]:
b

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])

In [195]:
#array attributes

In [ ]:
#transpose

In [199]:
arr=np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [201]:
arr.transpose()

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [203]:
arr.view()

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [211]:
arr.sort()

In [213]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])