In [1]:
#random number generations

In [3]:
import numpy as np

In [5]:
np.random.rand()             #uniform distribution

0.14533192418504548

In [7]:
np.random.randn()            #normal distribution

-1.4263633322185831

In [13]:
uniform=np.random.rand(3,3)

In [20]:
# np.where()

In [22]:
arr=np.array([1,2,3,4,5])

In [24]:
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [26]:
np.where(arr>2)

(array([2, 3, 4], dtype=int64),)

In [28]:
np.where(arr>2)

(array([2, 3, 4], dtype=int64),)

In [30]:
np.where(arr<2)

(array([0], dtype=int64),)

In [32]:
arr=np.array([1,2,3,4,5])

In [34]:
np.argmax(arr)

4

In [36]:
np.argmin(arr)

0

In [38]:
sorted_arr=np.array([1,3,5,7])

In [40]:
np.searchsorted(sorted_arr,100)

4

In [42]:
np.searchsorted(sorted_arr,2)

1

In [46]:
np.searchsorted(sorted_arr,4)

2

In [48]:
arr=np.array([1,2,3,4,5])

In [50]:
print("extract>3:",np.extract(arr>3,arr))

extract>3: [4 5]


In [ ]:
arr=np.array([1,2,3,4,5])

In [60]:
print("mean value:",np.mean(arr))

mean value: 3.0


In [62]:
np.mean(arr)

3.0

In [68]:
arr=np.array([1,2,3,4,5,6])

In [70]:
np.split(arr,3)

[array([1, 2]), array([3, 4]), array([5, 6])]

In [72]:
np.split(arr,2)

[array([1, 2, 3]), array([4, 5, 6])]

In [74]:
np.split(arr,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6])]

In [76]:
np.split(arr,[2,5])

[array([1, 2]), array([3, 4, 5]), array([6])]

In [80]:
matrix=np.array([[1,2,3],
                 [4,5,6]])

In [84]:
np.split(matrix,2,axis=0)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [86]:
np.split(matrix,3,axis=1)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [88]:
arr=np.array([3,1,2,6,4])

In [90]:
print("sorted copy:",np.sort(arr))

sorted copy: [1 2 3 4 6]


In [94]:
arr.sort()

In [96]:
print("sorted copy:",(arr))

sorted copy: [1 2 3 4 6]
